---
"adeploy server-scripts":
  tags:
    - prod
  stage: deploy
  script:
    - ANSIBLE_STDOUT_CALLBACK=actionable ansible-deploy server-scripts --ssh-common-args="-i /srv/docker/gitlab/keys/prod/id_rsa"
  when: manual
  only:
    - master
